name: Upload_Python_Package

on:
  workflow_run:
    workflows: ["Build_wheel"]
    types:
      - completed
    on:
      branches:
        - develop
        - main
      pull_requests:
        - merged

permissions:
  contents: read

jobs:
  deploy:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            workflow: wheels.yml
            name: '*.whl'
    - name: Install Twine
      run: pip install twine
    - name: Upload package to PyPI
      run: |
        twine upload *.whl
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}